
 Directory of C:\Users\Emre\Documents\ML_EEG\env

03/02/2019  03:08 PM    <DIR>          .
03/02/2019  03:08 PM    <DIR>          ..
03/18/2017  08:17 AM    <DIR>          Include
03/02/2019  03:08 PM    <DIR>          Lib
03/02/2019  03:08 PM                61 pip-selfcheck.json
03/02/2019  03:16 PM    <DIR>          Scripts
03/02/2019  03:07 PM    <DIR>          tcl
               1 File(s)             61 bytes
               6 Dir(s)  177,737,502,720 bytes free

C:\Users\Emre\Documents\ML_EEG\env>Scripts/activate
'Scripts' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Emre\Documents\ML_EEG\env>\Scripts\activate.bat
The system cannot find the path specified.

C:\Users\Emre\Documents\ML_EEG\env>cd Scripts

C:\Users\Emre\Documents\ML_EEG\env\Scripts>\activate.bat
'\activate.bat' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Emre\Documents\ML_EEG\env\Scripts>activate.bat

(env) C:\Users\Emre\Documents\ML_EEG\env\Scripts>cd ..

(env) C:\Users\Emre\Documents\ML_EEG\env>dir
 Volume in drive C has no label.
 Volume Serial Number is E8B5-F8DC

 Directory of C:\Users\Emre\Documents\ML_EEG\env

03/02/2019  03:08 PM    <DIR>          .
03/02/2019  03:08 PM    <DIR>          ..
03/18/2017  08:17 AM    <DIR>          Include
03/02/2019  03:08 PM    <DIR>          Lib
03/02/2019  03:08 PM                61 pip-selfcheck.json
03/02/2019  03:16 PM    <DIR>          Scripts
03/02/2019  03:07 PM    <DIR>          tcl
               1 File(s)             61 bytes
               6 Dir(s)  177,737,490,432 bytes free

(env) C:\Users\Emre\Documents\ML_EEG\env>cd ..

(env) C:\Users\Emre\Documents\ML_EEG>dir
 Volume in drive C has no label.
 Volume Serial Number is E8B5-F8DC

 Directory of C:\Users\Emre\Documents\ML_EEG

04/26/2019  11:35 PM    <DIR>          .
04/26/2019  11:35 PM    <DIR>          ..
04/27/2019  12:10 AM               205 .gitignore
03/23/2019  11:49 AM    <DIR>          data
03/02/2019  03:08 PM    <DIR>          env
03/23/2019  01:20 PM    <DIR>          gestures
04/27/2019  12:09 AM    <DIR>          images
03/02/2019  04:44 PM               664 README.md
03/23/2019  10:44 AM               352 requirements.txt
04/26/2019  11:35 PM    <DIR>          src
               3 File(s)          1,221 bytes
               7 Dir(s)  177,737,490,432 bytes free

(env) C:\Users\Emre\Documents\ML_EEG>pip install -r requirements.txt
Requirement already satisfied: absl-py==0.7.0 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 1)) (0.7.0)
Requirement already satisfied: astor==0.7.1 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 2)) (0.7.1)
Requirement already satisfied: gast==0.2.2 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 3)) (0.2.2)
Requirement already satisfied: grpcio==1.19.0 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 4)) (1.19.0)
Requirement already satisfied: h5py==2.9.0 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 5)) (2.9.0)
Requirement already satisfied: Keras-Applications==1.0.7 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 6)) (1.0.7)
Requirement already satisfied: Keras-Preprocessing==1.0.9 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 7)) (1.0.9)
Requirement already satisfied: Markdown==3.0.1 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 8)) (3.0.1)
Requirement already satisfied: matplotlib==3.0.3 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 9)) (3.0.3)
Requirement already satisfied: mock==2.0.0 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 10)) (2.0.0)
Requirement already satisfied: numpy==1.16.2 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 11)) (1.16.2)
Requirement already satisfied: pbr==5.1.3 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 12)) (5.1.3)
Requirement already satisfied: protobuf==3.7.0 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 13)) (3.7.0)
Requirement already satisfied: scipy==1.2.1 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 14)) (1.2.1)
Requirement already satisfied: six==1.12.0 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 15)) (1.12.0)
Requirement already satisfied: tensorboard==1.13.0 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 16)) (1.13.0)
Requirement already satisfied: tensorflow==1.13.1 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 17)) (1.13.1)
Requirement already satisfied: tensorflow-estimator==1.13.0 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 18)) (1.13.0)
Requirement already satisfied: termcolor==1.1.0 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 19)) (1.1.0)
Requirement already satisfied: Werkzeug==0.14.1 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 20)) (0.14.1)
Requirement already satisfied: cycler>=0.10 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from matplotlib==3.0.3->-r requirements.txt (line 9)) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from matplotlib==3.0.3->-r requirements.txt (line 9)) (1.0.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from matplotlib==3.0.3->-r requirements.txt (line 9)) (2.3.1)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from matplotlib==3.0.3->-r requirements.txt (line 9)) (2.8.0)
Requirement already satisfied: setuptools in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from protobuf==3.7.0->-r requirements.txt (line 13)) (40.8.0)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from tensorboard==1.13.0->-r requirements.txt (line 16)) (0.33.1)
You are using pip version 19.0.3, however version 19.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

(env) C:\Users\Emre\Documents\ML_EEG>dir
 Volume in drive C has no label.
 Volume Serial Number is E8B5-F8DC

 Directory of C:\Users\Emre\Documents\ML_EEG

04/26/2019  11:35 PM    <DIR>          .
04/26/2019  11:35 PM    <DIR>          ..
04/27/2019  12:10 AM               205 .gitignore
03/23/2019  11:49 AM    <DIR>          data
03/02/2019  03:08 PM    <DIR>          env
03/23/2019  01:20 PM    <DIR>          gestures
04/27/2019  12:09 AM    <DIR>          images
03/02/2019  04:44 PM               664 README.md
03/23/2019  10:44 AM               352 requirements.txt
04/26/2019  11:35 PM    <DIR>          src
               3 File(s)          1,221 bytes
               7 Dir(s)  177,706,483,712 bytes free

(env) C:\Users\Emre\Documents\ML_EEG>cd src

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Classifying gesture_1
Traceback (most recent call last):
  File "cnn.py", line 31, in <module>
    main()
  File "cnn.py", line 23, in main
    raw_img = np.genfromtext(ipath[0], delimiter="\t")[:,0:-1]
AttributeError: module 'numpy' has no attribute 'genfromtext'

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Classifying gesture_1
image dimensions are 64, 1987
Traceback (most recent call last):
  File "cnn.py", line 31, in <module>
    main()
  File "cnn.py", line 26, in main
    build_cnn()
NameError: name 'build_cnn' is not defined

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Classifying gesture_1
image dimensions are 64, 1987

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Classifying gesture_1
image dimensions are 64, 1987
Classifying gesture_1
image dimensions are 64, 1806
Classifying gesture_1
image dimensions are 64, 1468
Classifying gesture_1
image dimensions are 64, 1690
Classifying gesture_1
image dimensions are 64, 1578
Classifying gesture_1
image dimensions are 64, 1418

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Traceback (most recent call last):
  File "cnn_example.py", line 6, in <module>
    from keras.datasets import mnist
ImportError: No module named 'keras'

(env) C:\Users\Emre\Documents\ML_EEG\src>pip install -r requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
You are using pip version 19.0.3, however version 19.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

(env) C:\Users\Emre\Documents\ML_EEG\src>cd ..

(env) C:\Users\Emre\Documents\ML_EEG>pip install -r requirements.txt
Requirement already satisfied: absl-py==0.7.0 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 1)) (0.7.0)
Requirement already satisfied: astor==0.7.1 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 2)) (0.7.1)
Requirement already satisfied: gast==0.2.2 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 3)) (0.2.2)
Requirement already satisfied: grpcio==1.19.0 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 4)) (1.19.0)
Requirement already satisfied: h5py==2.9.0 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 5)) (2.9.0)
Collecting keras==2.2.4 (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/5e/10/aa32dad071ce52b5502266b5c659451cfd6ffcbf14e6c8c4f16c0ff5aaab/Keras-2.2.4-py2.py3-none-any.whl (312kB)
    100% |████████████████████████████████| 317kB 3.7MB/s
Requirement already satisfied: Keras-Applications==1.0.7 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 7)) (1.0.7)
Requirement already satisfied: Keras-Preprocessing==1.0.9 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 8)) (1.0.9)
Requirement already satisfied: Markdown==3.0.1 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 9)) (3.0.1)
Requirement already satisfied: matplotlib==3.0.3 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 10)) (3.0.3)
Requirement already satisfied: mock==2.0.0 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 11)) (2.0.0)
Requirement already satisfied: numpy==1.16.2 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 12)) (1.16.2)
Requirement already satisfied: pbr==5.1.3 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 13)) (5.1.3)
Requirement already satisfied: protobuf==3.7.0 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 14)) (3.7.0)
Requirement already satisfied: scipy==1.2.1 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 15)) (1.2.1)
Requirement already satisfied: six==1.12.0 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 16)) (1.12.0)
Requirement already satisfied: tensorboard==1.13.0 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 17)) (1.13.0)
Requirement already satisfied: tensorflow==1.13.1 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 18)) (1.13.1)
Requirement already satisfied: tensorflow-estimator==1.13.0 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 19)) (1.13.0)
Requirement already satisfied: termcolor==1.1.0 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 20)) (1.1.0)
Requirement already satisfied: Werkzeug==0.14.1 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from -r requirements.txt (line 21)) (0.14.1)
Collecting pyyaml (from keras==2.2.4->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/dd/74/82496ef0a3e0ec47f4c40ea19a9d7bf0371034d1e4dddda3fbc6f8898aed/PyYAML-5.1-cp35-cp35m-win_amd64.whl (208kB)
    100% |████████████████████████████████| 215kB 4.7MB/s
Requirement already satisfied: python-dateutil>=2.1 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from matplotlib==3.0.3->-r requirements.txt (line 10)) (2.8.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from matplotlib==3.0.3->-r requirements.txt (line 10)) (1.0.1)
Requirement already satisfied: cycler>=0.10 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from matplotlib==3.0.3->-r requirements.txt (line 10)) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from matplotlib==3.0.3->-r requirements.txt (line 10)) (2.3.1)
Requirement already satisfied: setuptools in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from protobuf==3.7.0->-r requirements.txt (line 14)) (40.8.0)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from tensorboard==1.13.0->-r requirements.txt (line 17)) (0.33.1)
Installing collected packages: pyyaml, keras
Successfully installed keras-2.2.4 pyyaml-5.1
You are using pip version 19.0.3, however version 19.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

(env) C:\Users\Emre\Documents\ML_EEG>python -m pip install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/f9/fb/863012b13912709c13cf5cfdbfb304fa6c727659d6290438e1a88df9d848/pip-19.1-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 4.2MB/s
Installing collected packages: pip
  Found existing installation: pip 19.0.3
    Uninstalling pip-19.0.3:
      Successfully uninstalled pip-19.0.3
Successfully installed pip-19.1

(env) C:\Users\Emre\Documents\ML_EEG>cd src

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.
Classifying gesture_1
image dimensions are 64, 1987
Classifying gesture_1
image dimensions are 64, 1806
Classifying gesture_1
image dimensions are 64, 1468
Classifying gesture_1
image dimensions are 64, 1690
Classifying gesture_1
image dimensions are 64, 1578
Classifying gesture_1
image dimensions are 64, 1418

(env) C:\Users\Emre\Documents\ML_EEG\src>
(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.
Classifying gesture_1
image dimensions are 64, 1987
Classifying gesture_1
image dimensions are 64, 1806
Classifying gesture_1
image dimensions are 64, 1468
Classifying gesture_1
image dimensions are 64, 1690
Classifying gesture_1
image dimensions are 64, 1578
Classifying gesture_1
image dimensions are 64, 1418

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
  File "cnn_example.py", line 6
    (X_train, y_train), (X_test, y_test) = mnist.load_data()
    ^
IndentationError: expected an indented block

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.
Downloading data from https://s3.amazonaws.com/img-datasets/mnist.npz
11493376/11490434 [==============================] - 1s 0us/step

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.
(28, 28)

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.
(28, 28)
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.
(28, 28)
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.
(28, 28)
Traceback (most recent call last):
  File "cnn_example.py", line 29, in <module>
    main()
  File "cnn_example.py", line 20, in main
    plt.imshow(X_train[0])
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\matplotlib\pyplot.py", line 2699, in imshow
    None else {}), **kwargs)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\matplotlib\__init__.py", line 1810, in inner
    return func(ax, *args, **kwargs)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\matplotlib\axes\_axes.py", line 5494, in imshow
    im.set_data(X)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\matplotlib\image.py", line 638, in set_data
    raise TypeError("Invalid dimensions for image data")
TypeError: Invalid dimensions for image data

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
  File "cnn_example.py", line 30
    model.add(Conv2D(64, kernel_size=3, activation=\u2019relu\u2019, input_shape=(28,28,1)))
                                                        ^
SyntaxError: invalid character in identifier

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.
(28, 28)
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 60000 samples, validate on 10000 samples
Epoch 1/3
2019-04-27 00:54:11.677116: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
60000/60000 [==============================] - 154s 3ms/step - loss: 13.4754 - acc: 0.1637 - val_loss: 13.2587 - val_acc: 0.1774
Epoch 2/3
60000/60000 [==============================] - 155s 3ms/step - loss: 13.5277 - acc: 0.1607 - val_loss: 14.4951 - val_acc: 0.1007
Epoch 3/3
60000/60000 [==============================] - 153s 3ms/step - loss: 13.8857 - acc: 0.1385 - val_loss: 14.3080 - val_acc: 0.1123
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x000001F81BFE9940>>
Traceback (most recent call last):
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\client\session.py", line 738, in __del__
TypeError: 'NoneType' object is not callable

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.
2019-04-27 10:32:06.714945: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2

(env) C:\Users\Emre\Documents\ML_EEG\src>git add -A

(env) C:\Users\Emre\Documents\ML_EEG\src>git push origin master
fatal: HttpRequestException encountered.
   An error occurred while sending the request.
Everything up-to-date

(env) C:\Users\Emre\Documents\ML_EEG\src>git commit -m "trying new cnn attempt"
[master 859929c] trying new cnn attempt
 8 files changed, 122 insertions(+), 7 deletions(-)
 create mode 100644 src/cnn.py
 create mode 100644 src/cnn_example.py

(env) C:\Users\Emre\Documents\ML_EEG\src>git push origin master
fatal: HttpRequestException encountered.
   An error occurred while sending the request.
Counting objects: 11, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (11/11), done.
Writing objects: 100% (11/11), 22.43 KiB | 3.74 MiB/s, done.
Total 11 (delta 6), reused 0 (delta 0)
remote: Resolving deltas: 100% (6/6), completed with 5 local objects.
To https://github.com/perlGivesMeNightmares/comp_5450_eeg.git
   cf00100..859929c  master -> master

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.
2019-04-27 10:40:20.007172: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.
(28, 28)
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 60000 samples, validate on 10000 samples
Epoch 1/3
2019-04-27 10:40:40.087417: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
60000/60000 [==============================] - 285s 5ms/step - loss: 0.1301 - acc: 0.9612 - val_loss: 0.0497 - val_acc: 0.9843
Epoch 2/3
 1728/60000 [..............................] - ETA: 2:35 - loss: 0.0473 - acc: 0.9867Traceback (most recent call last):
  File "cnn_example.py", line 48, in <module>
    main()
  File "cnn_example.py", line 44, in main
    model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=3)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
KeyboardInterrupt

(env) C:\Users\Emre\Documents\ML_EEG\src>git add -A

(env) C:\Users\Emre\Documents\ML_EEG\src>git commit -m "add readme"
[master ca28085] add readme
 2 files changed, 5 insertions(+), 2 deletions(-)

(env) C:\Users\Emre\Documents\ML_EEG\src>git push origin master
fatal: HttpRequestException encountered.
   An error occurred while sending the request.
Counting objects: 5, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 559 bytes | 559.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To https://github.com/perlGivesMeNightmares/comp_5450_eeg.git
   859929c..ca28085  master -> master

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.
[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9 4 0 9 1 1 2 4 3 2 7 3 8 6 9 0 5 6
 0 7 6 1 8 7 9 3 9 8 5 9 3 3 0 7 4 9 8 0 9 4 1 4 4 6 0 4 5 6 1 0 0 1 7 1 6
 3 0 2 1 1 7 9 0 2 6 7 8 3 9 0 4 6 7 4 6 8 0 7 8 3 1 5 7 1 7 1 1 6 3 0 2 9
 3 1 1 0 4 9 2 0 0 2 0 2 7 1 8 6 4 1 6 3 4 5 9 1 3 3 8 5 4 7 7 4 2 8 5 8 6
 7 3 4 6 1 9 9 6 0 3 7 2 8 2 9 4 4 6 4 9 7 0 9 2 9 5 1 5 9 1 2 3 2 3 5 9 1
 7 6 2 8 2 2 5 0 7 4 9 7 8 3 2 1 1 8 3 6 1 0 3 1 0 0 1 7 2 7 3 0 4 6 5 2 6
 4 7 1 8 9 9 3 0 7 1 0 2 0 3 5 4 6 5 8 6 3 7 5 8 0 9 1 0 3 1 2 2 3 3 6 4 7
 5 0 6 2 7 9 8 5 9 2 1 1 4 4 5 6 4 1 2 5 3 9 3 9 0 5 9 6 5 7 4 1 3 4 0 4 8
 0 4 3 6]

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.
[5 0 4 1 9 2 1 3 1 4]
<class 'numpy.uint8'>

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Classifying gesture_1
image dimensions are 64, 1987

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.
[5 0 4 1 9 2 1 3 1 4]
<class 'numpy.ndarray'>

(env) C:\Users\Emre\Documents\ML_EEG\src>pip freeze
absl-py==0.7.0
astor==0.7.1
cycler==0.10.0
gast==0.2.2
grpcio==1.19.0
h5py==2.9.0
Keras==2.2.4
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.9
kiwisolver==1.0.1
Markdown==3.0.1
matplotlib==3.0.3
mock==2.0.0
numpy==1.16.2
pbr==5.1.3
protobuf==3.7.0
pyparsing==2.3.1
python-dateutil==2.8.0
PyYAML==5.1
scipy==1.2.1
six==1.12.0
tensorboard==1.13.0
tensorflow==1.13.1
tensorflow-estimator==1.13.0
termcolor==1.1.0
Werkzeug==0.14.1

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
4

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
4

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
dict_keys(['__globals__', '__version__', '__header__', 'D'])

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
64

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
64
Traceback (most recent call last):
  File "cnn.py", line 76, in <module>
    main()
  File "cnn.py", line 19, in main
    print(len(training_data['lon']))
KeyError: 'lon'

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
64
<class 'numpy.ndarray'>

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
64
<class 'numpy.ndarray'>

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
64
1000

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
64
1000

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
dict_keys(['D', '__header__', '__version__', '__globals__'])
64
1000

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
dict_keys(['D', '__globals__', '__header__', '__version__'])
64
1000

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
dict_keys(['__header__', '__version__', 'D', '__globals__'])
64
1000

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
dict_keys(['__globals__', '__header__', '__version__', 'D'])
64
1000
Traceback (most recent call last):
  File "cnn.py", line 81, in <module>
    main()
  File "cnn.py", line 22, in main
    plt.imshow(training_data['D'])
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\matplotlib\pyplot.py", line 2699, in imshow
    None else {}), **kwargs)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\matplotlib\__init__.py", line 1810, in inner
    return func(ax, *args, **kwargs)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\matplotlib\axes\_axes.py", line 5494, in imshow
    im.set_data(X)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\matplotlib\image.py", line 638, in set_data
    raise TypeError("Invalid dimensions for image data")
TypeError: Invalid dimensions for image data

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Traceback (most recent call last):
  File "cnn.py", line 84, in <module>
    main()
  File "cnn.py", line 18, in main
    print(len())
TypeError: len() takes exactly one argument (0 given)

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
64
1000

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
64

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
1000

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
<class 'numpy.ndarray'>
1000

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
64
1000

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
64
1000
[3.6500e-04 5.0300e-04 8.4400e-04 5.0000e-05 8.8000e-05 2.4000e-04
 8.8200e-04 1.0700e-04 3.7000e-05 5.8300e-04 1.7600e-04 1.0000e-04
 1.7160e-03 1.2800e-04 5.0500e-04 3.2000e-05 8.7000e-05 4.3900e-04
 3.8400e-04 1.1900e-03 9.1000e-04 3.8500e-04 1.0400e-04 6.8000e-05
 1.6100e-04 1.8200e-04 1.2200e-04 1.4500e-04 3.6700e-04 3.5400e-04
 2.8800e-04 1.0000e-04 1.6400e-04 2.7100e-04 1.1600e-04 9.1000e-05
 9.6500e-04 1.9500e-04 1.8860e-03 1.0200e-04 8.8100e-04 1.9500e-04
 9.3000e-05 5.2000e-05 1.6200e-04 3.1000e-05 2.1900e-04 1.7600e-04
 4.8000e-05 7.7100e-04 1.0720e-03 5.4100e-04 5.3600e-04 7.2900e-04
 1.6030e-03 5.0900e-04 1.1960e-03 1.2640e-03 2.4980e-03 1.1000e-05
 1.4700e-03 3.5300e-04 4.4100e-04 1.8360e-03 4.4000e-04 4.7060e-03
 2.7000e-04 2.9000e-05 1.5200e-04 8.5400e-04 2.0000e-05 1.0600e-04
 9.8000e-05 3.2000e-05 1.5470e-03 5.4330e-03 1.8300e-04 3.2800e-03
 7.9200e-04 2.6380e-03 2.6240e-03 2.9120e-03 2.5080e-03 4.4500e-04
 9.9780e-03 1.0200e-04 1.9900e-04 8.7300e-04 3.8880e-03 5.0020e-03
 1.0600e-04 2.5550e-03 2.3200e-04 2.9610e-03 8.8200e-04 1.6540e-03
 7.0200e-04 2.2470e-03 1.7000e-04 9.0000e-06 4.9600e-04 1.7760e-03
 1.4500e-04 7.1000e-04 3.3460e-03 2.8050e-03 5.9100e-04 2.7800e-04
 2.3530e-03 4.6400e-04 1.3400e-04 1.2800e-04 4.0000e-04 2.5200e-04
 1.4960e-03 1.8450e-03 4.3400e-04 1.0900e-04 1.1520e-03 5.1500e-04
 1.1500e-04 1.1120e-03 1.0000e-06 4.3000e-05 1.7700e-04 3.2300e-04
 3.0760e-03 3.1900e-04 2.6300e-04 9.4000e-05 1.0200e-03 2.7200e-04
 2.7600e-04 7.5500e-04 1.0780e-03 2.3300e-04 1.4060e-03 3.6000e-05
 3.0000e-04 9.4000e-05 1.6000e-05 8.8400e-04 2.1300e-04 8.4000e-05
 1.5400e-04 3.4620e-03 2.7000e-05 1.2000e-05 2.8700e-04 4.7130e-03
 3.2430e-03 7.5000e-05 3.1540e-03 1.3900e-04 4.8450e-03 2.1800e-04
 5.4800e-04 4.4700e-04 5.3150e-03 1.1670e-03 1.8400e-04 1.1210e-03
 6.5000e-05 4.1200e-04 3.1300e-04 2.3100e-04 1.1700e-04 7.5000e-05
 1.1000e-05 4.2400e-04 6.3100e-04 3.2400e-04 1.1000e-03 9.1400e-04
 5.0900e-04 3.3310e-03 1.1990e-03 1.0000e-04 3.9000e-05 1.8100e-04
 1.5200e-04 7.8200e-04 9.4700e-04 1.2400e-04 1.4410e-03 7.3900e-04
 2.0000e-04 1.7200e-04 8.7900e-04 4.4300e-04 3.1400e-04 1.7210e-03
 2.1280e-03 1.0200e-04 6.0580e-03 3.6850e-03 4.9200e-04 6.6000e-05
 3.4600e-04 4.5000e-04 5.3600e-04 1.3000e-05 3.9100e-04 1.8370e-03
 1.8920e-03 1.0410e-03 1.3000e-05 2.4500e-04 2.8300e-04 2.3800e-04
 1.2900e-04 5.5100e-04 1.1250e-03 8.4000e-05 9.9200e-04 1.2400e-04
 1.9600e-04 5.1000e-05 6.7700e-04 9.8000e-04 9.6700e-04 1.2050e-03
 1.3000e-05 8.6000e-05 1.8550e-03 3.6300e-04 2.0210e-03 1.2300e-04
 5.6000e-05 1.7400e-04 8.6800e-04 7.1900e-04 2.3840e-03 1.5700e-03
 1.3800e-04 1.4130e-03 1.4523e-02 6.3800e-04 1.4000e-04 1.4810e-03
 4.1000e-05 4.1800e-04 1.6000e-05 2.7700e-04 5.0060e-03 1.5260e-03
 5.5800e-04 7.1000e-05 6.8000e-05 3.4000e-04 1.0800e-04 3.6700e-04
 1.7880e-03 1.1860e-03 4.9400e-04 4.3000e-04 3.5000e-05 1.5700e-04
 4.5000e-04 4.5900e-04 1.8300e-04 1.8400e-04 5.7100e-04 5.2100e-04
 2.9400e-04 1.9600e-04 4.3300e-04 1.8700e-04 2.6400e-04 1.1000e-04
 1.9400e-04 3.0500e-04 8.7800e-04 1.6300e-03 3.8500e-04 2.3700e-04
 5.5300e-04 2.3200e-04 3.9000e-05 1.7500e-04 2.3000e-04 2.7380e-03
 1.0800e-04 1.2500e-04 2.9000e-04 8.1000e-05 5.3000e-05 6.9600e-04
 1.7300e-04 1.4910e-03 3.0640e-03 3.4200e-04 5.7100e-04 1.4380e-03
 8.1000e-04 1.3780e-03 5.1960e-03 8.5400e-04 2.8000e-05 1.7900e-04]

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
64
1000
300

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
64
1000
300
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
64
1000
300
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
64
1000
300
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>
Traceback (most recent call last):
  File "cnn.py", line 94, in <module>
    main()
  File "cnn.py", line 32, in main
    plt.imshow(data['D'][0])
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
64
1000
300
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>
300

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
64
1000
300
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>
300

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
64
1000
300
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>
Traceback (most recent call last):
  File "cnn.py", line 96, in <module>
    main()
  File "cnn.py", line 30, in main
    print(len(data)[0])
TypeError: 'int' object is not subscriptable

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
(64, 1000, 300)
(300, 1000, 64)

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
(64, 1000, 300)
(300, 1000, 64)

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.
(60000, 28, 28)

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.
(60000,)

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.
(60000,)

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.
5

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Traceback (most recent call last):
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\scipy\io\matlab\mio.py", line 31, in _open_file
    return open(file_like, 'rb'), True
FileNotFoundError: [Errno 2] No such file or directory: '../images/TestData.mat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cnn.py", line 94, in <module>
    main()
  File "cnn.py", line 18, in main
    test_data = scipy.io.loadmat('../images/TestData.mat')['D']
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\scipy\io\matlab\mio.py", line 207, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\scipy\io\matlab\mio.py", line 62, in mat_reader_factory
    byte_stream, file_opened = _open_file(file_name, appendmat)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\scipy\io\matlab\mio.py", line 37, in _open_file
    return open(file_like, 'rb'), True
FileNotFoundError: [Errno 2] No such file or directory: '../images/TestData.mat'

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Traceback (most recent call last):
  File "cnn.py", line 94, in <module>
    main()
  File "cnn.py", line 18, in main
    test_data = scipy.io.loadmat('../images/TestingData.mat')['D']
KeyError: 'D'

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Traceback (most recent call last):
  File "cnn.py", line 96, in <module>
    main()
  File "cnn.py", line 18, in main
    test_data = scipy.io.loadmat('../images/TestingData.mat')['D']
KeyError: 'D'

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
dict_keys(['__header__', 'B', '__version__', '__globals__'])
Traceback (most recent call last):
  File "cnn.py", line 95, in <module>
    main()
  File "cnn.py", line 22, in main
    data = test_data.transpose(2, 1, 0)
AttributeError: 'dict' object has no attribute 'transpose'

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
(64, 1000, 120)

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Traceback (most recent call last):
  File "cnn.py", line 100, in <module>
    main()
  File "cnn.py", line 23, in main
    training_labels, testing_labels = create_labels()
  File "cnn.py", line 86, in create_labels
    for i in range(len(labels)):
NameError: name 'labels' is not defined

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Traceback (most recent call last):
  File "cnn.py", line 100, in <module>
    main()
  File "cnn.py", line 23, in main
    training_labels, testing_labels = create_labels()
  File "cnn.py", line 92, in create_labels
    for i in range(len(testing_labels)):
NameError: name 'testing_labels' is not defined

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
training: (300,)
testing: (120,)

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Traceback (most recent call last):
  File "cnn.py", line 81, in <module>
    main()
  File "cnn.py", line 25, in main
    build_cnn(training_data, training_lables, testing_data, testing_lables)
NameError: name 'training_lables' is not defined

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py

(env) C:\Users\Emre\Documents\ML_EEG\src>pip freeze
absl-py==0.7.0
astor==0.7.1
cycler==0.10.0
gast==0.2.2
grpcio==1.19.0
h5py==2.9.0
Keras==2.2.4
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.9
kiwisolver==1.0.1
Markdown==3.0.1
matplotlib==3.0.3
mock==2.0.0
numpy==1.16.2
pbr==5.1.3
protobuf==3.7.0
pyparsing==2.3.1
python-dateutil==2.8.0
PyYAML==5.1
scipy==1.2.1
six==1.12.0
tensorboard==1.13.0
tensorflow==1.13.1
tensorflow-estimator==1.13.0
termcolor==1.1.0
Werkzeug==0.14.1

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Traceback (most recent call last):
  File "cnn.py", line 81, in <module>
    main()
  File "cnn.py", line 25, in main
    build_cnn(training_data, training_labels, testing_data, testing_lables)
NameError: name 'testing_lables' is not defined

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Traceback (most recent call last):
  File "cnn.py", line 81, in <module>
    main()
  File "cnn.py", line 25, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 39, in build_cnn
    X_train = X_train.reshape(300,48,48,1) / 256
ValueError: cannot reshape array of size 19200000 into shape (300,48,48,1)

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
(1000, 64)
Traceback (most recent call last):
  File "cnn.py", line 81, in <module>
    main()
  File "cnn.py", line 25, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 39, in build_cnn
    X_train = X_train.reshape(300,48,48,1) / 256
ValueError: cannot reshape array of size 19200000 into shape (300,48,48,1)

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
(1000, 64)
Traceback (most recent call last):
  File "cnn.py", line 83, in <module>
    main()
  File "cnn.py", line 25, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 45, in build_cnn
    y_train = to_categorical(y_train)
NameError: name 'to_categorical' is not defined

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
(1000, 64)
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "cnn.py", line 86, in <module>
    main()
  File "cnn.py", line 28, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 64, in build_cnn
    model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=1)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training.py", line 952, in fit
    batch_size=batch_size)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected conv2d_1_input to have 4 dimensions, but got array with shape (300, 1000, 64)

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.
(60000, 28, 28)
(60000, 28, 28, 1)

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
(300, 1000, 64)
(300, 1000, 64)
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "cnn.py", line 88, in <module>
    main()
  File "cnn.py", line 28, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 66, in build_cnn
    model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=1)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training.py", line 952, in fit
    batch_size=batch_size)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected conv2d_1_input to have 4 dimensions, but got array with shape (300, 1000, 64)

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
(300, 1000, 64)
(300, 1000, 64, 1)

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
(300, 1000, 64, 1)
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "cnn.py", line 83, in <module>
    main()
  File "cnn.py", line 28, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 61, in build_cnn
    model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=1)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training.py", line 952, in fit
    batch_size=batch_size)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training.py", line 789, in _standardize_user_data
    exception_prefix='target')
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training_utils.py", line 138, in standardize_input_data
    str(data_shape))
ValueError: Error when checking target: expected dense_1 to have shape (10,) but got array with shape (8,)

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.
(60000, 28, 28, 1)
(60000, 10)

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
(300, 1000, 64, 1)
(300, 8)

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has shape (300, 1000, 64) and value 0.000365
training labels has shape (300,) and value 2.0
Traceback (most recent call last):
  File "cnn.py", line 90, in <module>
    main()
  File "cnn.py", line 31, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 45, in build_cnn
    print("reshaped training data has shape %s and value %s" % (str(training_data.shape), training_data[0][0][0]))
NameError: name 'training_data' is not defined

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has shape (300, 1000, 64) and value 0.000365
training labels has shape (300,) and value 2.0
reshaped training data has shape (300, 1000, 64, 1) and value [1.42578125e-06]
[[0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has shape (300, 1000, 64) and value 0.000365
training labels has shape (300,) and value 2.0
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5. 5. 5. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6.
 6. 6. 6. 6. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has shape (300, 1000, 64) and value 0.000365
training labels has shape (300,) and value 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has shape (300, 1000, 64) and value 0.000365
training labels has shape (300,) and value 0.0
reshaped training data has shape (300, 1000, 64, 1) and value [1.42578125e-06]
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has shape (300, 1000, 64) and value 0.000365
training labels has shape (300,) and value 0.0
reshaped training data has shape (300, 1000, 64, 1) and value [1.42578125e-06]
Traceback (most recent call last):
  File "cnn.py", line 87, in <module>
    main()
  File "cnn.py", line 31, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 51, in build_cnn
    print("training labels has shape %s and value %s" % (str(training_labels.shape), training_labels[0]))
NameError: name 'training_labels' is not defined

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has shape (300, 1000, 64) and value 0.000365
training labels has shape (300,) and value 0.0
reshaped training data has shape (300, 1000, 64, 1) and value [1.42578125e-06]
training labels has shape (300, 6) and value [1. 0. 0. 0. 0. 0.]
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "cnn.py", line 87, in <module>
    main()
  File "cnn.py", line 31, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 65, in build_cnn
    model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=1)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training.py", line 952, in fit
    batch_size=batch_size)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training.py", line 789, in _standardize_user_data
    exception_prefix='target')
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training_utils.py", line 138, in standardize_input_data
    str(data_shape))
ValueError: Error when checking target: expected dense_1 to have shape (10,) but got array with shape (6,)

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has shape (300, 1000, 64) and value 0.000365
training labels has shape (300,) and value 0.0
reshaped training data has shape (300, 1000, 64, 1) and value [1.42578125e-06]
training labels has shape (300, 6) and value [1. 0. 0. 0. 0. 0.]
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 300 samples, validate on 120 samples
Epoch 1/1
2019-04-27 12:17:26.920712: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
300/300 [==============================] - 76s 253ms/step - loss: 1.8245 - acc: 0.1400 - val_loss: 1.7918 - val_acc: 0.1667

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has shape (300, 1000, 64) and value 0.000365
training labels has shape (300,) and value 1.0
reshaped training data has shape (300, 1000, 64, 1) and value [1.42578125e-06]
training labels has shape (300, 7) and value [0. 1. 0. 0. 0. 0. 0.]
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\ops.py", line 1659, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Negative dimension size caused by subtracting 953 from 64 for 'conv2d_1/convolution' (op: 'Conv2D') with input shapes: [?,1000,64,1], [17,953,1,64].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cnn.py", line 83, in <module>
    main()
  File "cnn.py", line 26, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 51, in build_cnn
    model.add(Conv2D(64, kernel_size=(17,953), activation='relu', input_shape=(1000,64,1)))
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\sequential.py", line 165, in add
    layer(x)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\layers\convolutional.py", line 171, in call
    dilation_rate=self.dilation_rate)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py", line 3650, in conv2d
    data_format=tf_data_format)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 851, in convolution
    return op(input, filter)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 966, in __call__
    return self.conv_op(inp, filter)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 591, in __call__
    return self.call(inp, filter)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 208, in __call__
    name=self.name)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1112, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\ops.py", line 1823, in __init__
    control_input_ops)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Negative dimension size caused by subtracting 953 from 64 for 'conv2d_1/convolution' (op: 'Conv2D') with input shapes: [?,1000,64,1], [17,953,1,64].

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has shape (300, 1000, 64) and value 0.000365
training labels has shape (300,) and value 1.0
reshaped training data has shape (300, 1000, 64, 1) and value [1.42578125e-06]
training labels has shape (300, 7) and value [0. 1. 0. 0. 0. 0. 0.]
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "cnn.py", line 83, in <module>
    main()
  File "cnn.py", line 26, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 60, in build_cnn
    model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=1)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training.py", line 952, in fit
    batch_size=batch_size)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training.py", line 789, in _standardize_user_data
    exception_prefix='target')
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training_utils.py", line 138, in standardize_input_data
    str(data_shape))
ValueError: Error when checking target: expected dense_1 to have shape (6,) but got array with shape (7,)

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has shape (300, 1000, 64) and value 0.000365
training labels has shape (300,) and value 0.0
reshaped training data has shape (300, 1000, 64, 1) and value [1.42578125e-06]
training labels has shape (300, 6) and value [1. 0. 0. 0. 0. 0.]
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 300 samples, validate on 120 samples
Epoch 1/1
2019-04-27 12:38:31.263201: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
300/300 [==============================] - 113s 377ms/step - loss: 1.7939 - acc: 0.1500 - val_loss: 1.7918 - val_acc: 0.1667

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has shape (300, 1000, 64) and value 0.000365
training labels has shape (300,) and value 0.0
[[[3.43750000e-07]
  [3.51562500e-08]
  [4.29687500e-08]
  ...
  [1.40585938e-04]
  [3.59734375e-04]
  [6.87574219e-04]]

 [[3.51562500e-07]
  [2.73437500e-08]
  [5.07812500e-08]
  ...
  [1.31531250e-04]
  [3.42109375e-04]
  [7.20769531e-04]]

 [[3.59375000e-07]
  [1.95312500e-08]
  [6.25000000e-08]
  ...
  [1.23253906e-04]
  [3.24796875e-04]
  [7.53312500e-04]]

 ...

 [[7.57812500e-07]
  [1.37890625e-06]
  [9.80468750e-07]
  ...
  [1.59945313e-04]
  [9.68253906e-04]
  [2.63187891e-03]]

 [[7.77343750e-07]
  [1.43750000e-06]
  [1.00390625e-06]
  ...
  [1.69394531e-04]
  [1.01025781e-03]
  [2.71262891e-03]]

 [[8.00781250e-07]
  [1.49609375e-06]
  [1.01953125e-06]
  ...
  [1.78539062e-04]
  [1.05279687e-03]
  [2.79232422e-03]]]

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has shape (300, 1000, 64) and value 0.000365
training labels has shape (300,) and value 0.0

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has shape (300, 1000, 64) and value 0.000365
training labels has shape (300,) and value 0.0
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 300 samples, validate on 120 samples
Epoch 1/1
2019-04-27 12:45:52.164098: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
300/300 [==============================] - 74s 247ms/step - loss: 12.7435 - acc: 0.1567 - val_loss: 13.5661 - val_acc: 0.1583

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\scipy\io\matlab\mio.py", line 31, in _open_file
    return open(file_like, 'rb'), True
FileNotFoundError: [Errno 2] No such file or directory: '../images/yourmother.mat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cnn.py", line 82, in <module>
    main()
  File "cnn.py", line 14, in main
    all_data = scipy.io.loadmat('../images/yourmother.mat')
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\scipy\io\matlab\mio.py", line 207, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\scipy\io\matlab\mio.py", line 62, in mat_reader_factory
    byte_stream, file_opened = _open_file(file_name, appendmat)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\scipy\io\matlab\mio.py", line 37, in _open_file
    return open(file_like, 'rb'), True
FileNotFoundError: [Errno 2] No such file or directory: '../images/yourmother.mat'

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
dict_keys(['B', '__version__', '__globals__', '__header__'])

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 378 samples, validate on 42 samples
Epoch 1/2
2019-04-27 12:55:22.735580: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "cnn.py", line 72, in <module>
    main()
  File "cnn.py", line 23, in main
    build_cnn(data, labels)
  File "cnn.py", line 54, in build_cnn
    h = model.fit(X_train, Y_train, batch_size=2, epochs=2, validation_split=0.1)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
KeyboardInterrupt

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 378 samples, validate on 42 samples
Epoch 1/2
2019-04-27 12:55:54.991400: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
126/378 [=========>....................] - ETA: 1:29 - loss: 13.5932 - acc: 0.1429Traceback (most recent call last):
  File "cnn.py", line 72, in <module>
    main()
  File "cnn.py", line 23, in main
    build_cnn(data, labels)
  File "cnn.py", line 54, in build_cnn
    h = model.fit(X_train, Y_train, batch_size=2, epochs=2, validation_split=0.1)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
KeyboardInterrupt

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 378 samples, validate on 42 samples
Epoch 1/2
2019-04-27 12:56:56.326745: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
378/378 [==============================] - 106s 280ms/step - loss: 1.8010 - acc: 0.1640 - val_loss: 1.8414 - val_acc: 0.0000e+00
Epoch 2/2
378/378 [==============================] - 111s 293ms/step - loss: 1.7847 - acc: 0.1693 - val_loss: 1.8875 - val_acc: 0.0000e+00

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "cnn.py", line 76, in <module>
    main()
  File "cnn.py", line 24, in main
    Random(4).shuffle(data)
NameError: name 'Random' is not defined

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 378 samples, validate on 42 samples
Epoch 1/2
2019-04-27 13:13:08.456568: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
378/378 [==============================] - 109s 289ms/step - loss: 1.7929 - acc: 0.1534 - val_loss: 1.7931 - val_acc: 0.0952
Epoch 2/2
108/378 [=======>......................] - ETA: 1:15 - loss: 1.7923 - acc: 0.1574Traceback (most recent call last):
  File "cnn.py", line 76, in <module>
    main()
  File "cnn.py", line 27, in main
    build_cnn(data, labels)
  File "cnn.py", line 58, in build_cnn
    h = model.fit(X_train, Y_train, batch_size=4, epochs=2, validation_split=0.1)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
KeyboardInterrupt

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "cnn.py", line 100, in <module>
    main()
  File "cnn.py", line 28, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 43, in build_cnn
    X_test = X_test.reshape(120,1000,64,1) * 1000 if X_test else None
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
[[[8.80000e-02]
  [9.00000e-03]
  [1.10000e-02]
  ...
  [3.59900e+01]
  [9.20920e+01]
  [1.76019e+02]]

 [[9.00000e-02]
  [7.00000e-03]
  [1.30000e-02]
  ...
  [3.36720e+01]
  [8.75800e+01]
  [1.84517e+02]]

 [[9.20000e-02]
  [5.00000e-03]
  [1.60000e-02]
  ...
  [3.15530e+01]
  [8.31480e+01]
  [1.92848e+02]]

 ...

 [[1.94000e-01]
  [3.53000e-01]
  [2.51000e-01]
  ...
  [4.09460e+01]
  [2.47873e+02]
  [6.73761e+02]]

 [[1.99000e-01]
  [3.68000e-01]
  [2.57000e-01]
  ...
  [4.33650e+01]
  [2.58626e+02]
  [6.94433e+02]]

 [[2.05000e-01]
  [3.83000e-01]
  [2.61000e-01]
  ...
  [4.57060e+01]
  [2.69516e+02]
  [7.14835e+02]]]

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 300 samples, validate on 120 samples
Epoch 1/1
2019-04-27 13:24:22.074091: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
300/300 [==============================] - 100s 334ms/step - loss: 1.7771 - acc: 0.1967 - val_loss: 1.7700 - val_acc: 0.1250

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 300 samples, validate on 120 samples
Epoch 1/1
2019-04-27 13:28:47.212460: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
300/300 [==============================] - 93s 309ms/step - loss: 1.8104 - acc: 0.1567 - val_loss: 1.7918 - val_acc: 0.1667

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
[[3.65000e-04 8.20000e-05 5.60000e-05 ... 1.24154e-01 4.02800e-03
  2.21982e-01]
 [3.53000e-04 8.30000e-05 5.90000e-05 ... 1.30080e-01 3.89200e-03
  2.29304e-01]
 [3.41000e-04 8.40000e-05 6.20000e-05 ... 1.36092e-01 4.65800e-03
  2.37133e-01]
 ...
 [1.17200e-03 1.26000e-04 2.30000e-04 ... 1.49235e-01 7.96680e-02
  1.96390e-01]
 [1.20600e-03 1.42000e-04 2.38000e-04 ... 1.53459e-01 9.07380e-02
  2.00066e-01]
 [1.23900e-03 1.60000e-04 2.46000e-04 ... 1.57782e-01 1.02144e-01
  2.03987e-01]]

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
1.0

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 300 samples, validate on 120 samples
Epoch 1/1
2019-04-27 13:40:14.805055: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
300/300 [==============================] - 112s 373ms/step - loss: 13.3984 - acc: 0.1633 - val_loss: 13.4317 - val_acc: 0.1667

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
[[[9.3440000e-02]
  [2.0992000e-02]
  [1.4336000e-02]
  ...
  [3.1783424e+01]
  [1.0311680e+00]
  [5.6827392e+01]]

 [[9.0368000e-02]
  [2.1248000e-02]
  [1.5104000e-02]
  ...
  [3.3300480e+01]
  [9.9635200e-01]
  [5.8701824e+01]]

 [[8.7296000e-02]
  [2.1504000e-02]
  [1.5872000e-02]
  ...
  [3.4839552e+01]
  [1.1924480e+00]
  [6.0706048e+01]]

 ...

 [[3.0003200e-01]
  [3.2256000e-02]
  [5.8880000e-02]
  ...
  [3.8204160e+01]
  [2.0395008e+01]
  [5.0275840e+01]]

 [[3.0873600e-01]
  [3.6352000e-02]
  [6.0928000e-02]
  ...
  [3.9285504e+01]
  [2.3228928e+01]
  [5.1216896e+01]]

 [[3.1718400e-01]
  [4.0960000e-02]
  [6.2976000e-02]
  ...
  [4.0392192e+01]
  [2.6148864e+01]
  [5.2220672e+01]]]

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
[[[9.3440000e-02]
  [2.0992000e-02]
  [1.4336000e-02]
  ...
  [3.1783424e+01]
  [1.0311680e+00]
  [5.6827392e+01]]

 [[9.0368000e-02]
  [2.1248000e-02]
  [1.5104000e-02]
  ...
  [3.3300480e+01]
  [9.9635200e-01]
  [5.8701824e+01]]

 [[8.7296000e-02]
  [2.1504000e-02]
  [1.5872000e-02]
  ...
  [3.4839552e+01]
  [1.1924480e+00]
  [6.0706048e+01]]

 ...

 [[3.0003200e-01]
  [3.2256000e-02]
  [5.8880000e-02]
  ...
  [3.8204160e+01]
  [2.0395008e+01]
  [5.0275840e+01]]

 [[3.0873600e-01]
  [3.6352000e-02]
  [6.0928000e-02]
  ...
  [3.9285504e+01]
  [2.3228928e+01]
  [5.1216896e+01]]

 [[3.1718400e-01]
  [4.0960000e-02]
  [6.2976000e-02]
  ...
  [4.0392192e+01]
  [2.6148864e+01]
  [5.2220672e+01]]]

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "cnn.py", line 102, in <module>
    main()
  File "cnn.py", line 32, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 44, in build_cnn
    plt.imshow(X_train[0])
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\matplotlib\pyplot.py", line 2699, in imshow
    None else {}), **kwargs)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\matplotlib\__init__.py", line 1810, in inner
    return func(ax, *args, **kwargs)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\matplotlib\axes\_axes.py", line 5494, in imshow
    im.set_data(X)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\matplotlib\image.py", line 638, in set_data
    raise TypeError("Invalid dimensions for image data")
TypeError: Invalid dimensions for image data

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 300 samples, validate on 120 samples
Epoch 1/5
2019-04-27 14:04:40.922803: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
300/300 [==============================] - 67s 223ms/step - loss: 1.7119 - acc: 0.2467 - val_loss: 1.5638 - val_acc: 0.3167
Epoch 2/5
300/300 [==============================] - 66s 219ms/step - loss: 1.2232 - acc: 0.5200 - val_loss: 1.7228 - val_acc: 0.2583
Epoch 3/5
300/300 [==============================] - 65s 218ms/step - loss: 0.8885 - acc: 0.6767 - val_loss: 2.6211 - val_acc: 0.2917
Epoch 4/5
300/300 [==============================] - 66s 219ms/step - loss: 0.5416 - acc: 0.8167 - val_loss: 3.4099 - val_acc: 0.2833
Epoch 5/5
300/300 [==============================] - 66s 220ms/step - loss: 0.2666 - acc: 0.9200 - val_loss: 4.1837 - val_acc: 0.2500

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 300 samples, validate on 120 samples
Epoch 1/8
2019-04-27 14:14:17.108316: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
300/300 [==============================] - 67s 224ms/step - loss: 1.7246 - acc: 0.2600 - val_loss: 1.6215 - val_acc: 0.2667
Epoch 2/8
300/300 [==============================] - 67s 225ms/step - loss: 1.1919 - acc: 0.5133 - val_loss: 1.8874 - val_acc: 0.2583
Epoch 3/8
300/300 [==============================] - 65s 218ms/step - loss: 0.8184 - acc: 0.7033 - val_loss: 2.4528 - val_acc: 0.2417
Epoch 4/8
300/300 [==============================] - 66s 218ms/step - loss: 0.4732 - acc: 0.8600 - val_loss: 3.6487 - val_acc: 0.2583
Epoch 5/8
300/300 [==============================] - 65s 218ms/step - loss: 0.2596 - acc: 0.9200 - val_loss: 4.2135 - val_acc: 0.2667
Epoch 6/8
300/300 [==============================] - 66s 219ms/step - loss: 0.1377 - acc: 0.9567 - val_loss: 5.1769 - val_acc: 0.2417
Epoch 7/8
300/300 [==============================] - 65s 218ms/step - loss: 0.1043 - acc: 0.9733 - val_loss: 5.9746 - val_acc: 0.2667
Epoch 8/8
300/300 [==============================] - 66s 221ms/step - loss: 0.0558 - acc: 0.9900 - val_loss: 6.1122 - val_acc: 0.2833

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "cnn.py", line 113, in <module>
    main()
  File "cnn.py", line 18, in main
    create_test_data(data)
  File "cnn.py", line 93, in create_test_data
    for i in range(test_set):
TypeError: only integer scalar arrays can be converted to a scalar index

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "cnn.py", line 113, in <module>
    main()
  File "cnn.py", line 18, in main
    create_test_data(data)
  File "cnn.py", line 95, in create_test_data
    validation_idx.append(x in range (i, i+10))
NameError: name 'x' is not defined

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428]

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359]

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "cnn.py", line 111, in <module>
    len(test_data) / 6
NameError: name 'test_data' is not defined

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
26879940

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
420

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359]
420

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359]
420
26879940

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359]
420
26879999
26879940

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359]
420
419
26879940

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359]
420
360

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
60

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "cnn.py", line 102, in <module>
    main()
  File "cnn.py", line 28, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 34, in build_cnn
    X_train = X_train.reshape(300,1000,64,1)
ValueError: cannot reshape array of size 23040000 into shape (300,1000,64,1)

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has 360, validation data has 60
Traceback (most recent call last):
  File "cnn.py", line 104, in <module>
    main()
  File "cnn.py", line 28, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 34, in build_cnn
    X_train = X_train.reshape(300,1000,64,1)
ValueError: cannot reshape array of size 23040000 into shape (300,1000,64,1)

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has 360, validation data has 60
Traceback (most recent call last):
  File "cnn.py", line 104, in <module>
    main()
  File "cnn.py", line 28, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 34, in build_cnn
    X_train = X_train.reshape(len(X_train),1000,64,1)
ValueError: cannot reshape array of size 23040000 into shape (64,1000,64,1)

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has 360, validation data has 60
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 360 samples, validate on 60 samples
Epoch 1/8
2019-04-27 14:54:06.599001: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
360/360 [==============================] - 75s 208ms/step - loss: 1.7057 - acc: 0.2694 - val_loss: 1.5074 - val_acc: 0.2500
Epoch 2/8
360/360 [==============================] - 85s 237ms/step - loss: 1.2555 - acc: 0.5000 - val_loss: 1.6746 - val_acc: 0.3500
Epoch 3/8
360/360 [==============================] - 75s 210ms/step - loss: 0.8975 - acc: 0.6556 - val_loss: 1.9792 - val_acc: 0.3500
Epoch 4/8
360/360 [==============================] - 77s 213ms/step - loss: 0.6264 - acc: 0.7806 - val_loss: 2.4067 - val_acc: 0.3000
Epoch 5/8
360/360 [==============================] - 76s 211ms/step - loss: 0.3419 - acc: 0.8917 - val_loss: 4.0765 - val_acc: 0.3667
Epoch 6/8
360/360 [==============================] - 75s 209ms/step - loss: 0.1769 - acc: 0.9444 - val_loss: 4.6208 - val_acc: 0.3167
Epoch 7/8
 64/360 [====>.........................] - ETA: 59s - loss: 0.0366 - acc: 1.0000 Traceback (most recent call last):
  File "cnn.py", line 104, in <module>
    main()
  File "cnn.py", line 28, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 59, in build_cnn
    model.fit(X_train, y_train, batch_size=8, validation_data=(X_test, y_test), epochs=8)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
KeyboardInterrupt

(env) C:\Users\Emre\Documents\ML_EEG\src>git add -A

(env) C:\Users\Emre\Documents\ML_EEG\src>git commit -m "holy cow this actually works"
[master eabfd92] holy cow this actually works
 4 files changed, 115 insertions(+), 74 deletions(-)
 create mode 100644 results.PNG
 rewrite src/cnn.py (69%)
 copy src/{cnn.py => cnn_old_format.py} (95%)

(env) C:\Users\Emre\Documents\ML_EEG\src>git push origin master
fatal: HttpRequestException encountered.
   An error occurred while sending the request.
Counting objects: 7, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 23.22 KiB | 5.81 MiB/s, done.
Total 7 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/perlGivesMeNightmares/comp_5450_eeg.git
   ca28085..eabfd92  master -> master

(env) C:\Users\Emre\Documents\ML_EEG\src>git push origin master
fatal: HttpRequestException encountered.
   An error occurred while sending the request.
Everything up-to-date

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has 360, validation data has 60
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 360 samples, validate on 60 samples
Epoch 1/8
2019-04-27 15:07:45.930083: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
360/360 [==============================] - 93s 257ms/step - loss: 1.7144 - acc: 0.2972 - val_loss: 1.5533 - val_acc: 0.3167
Epoch 2/8
360/360 [==============================] - 91s 252ms/step - loss: 1.2797 - acc: 0.4750 - val_loss: 1.6350 - val_acc: 0.2833
Epoch 3/8
136/360 [==========>...................] - ETA: 54s - loss: 0.8817 - acc: 0.7206Traceback (most recent call last):
  File "cnn.py", line 98, in <module>
    main()
  File "cnn.py", line 28, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 53, in build_cnn
    model.fit(X_train, y_train, batch_size=8, validation_data=(X_test, y_test), epochs=8)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
KeyboardInterrupt

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has 360, validation data has 60
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "cnn.py", line 99, in <module>
    main()
  File "cnn.py", line 28, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 46, in build_cnn
    model.add(MaxPooling2D(pool_size=(2, 2)))
NameError: name 'MaxPooling2D' is not defined

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has 360, validation data has 60
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 360 samples, validate on 60 samples
Epoch 1/8
2019-04-27 15:14:03.945169: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
360/360 [==============================] - 86s 238ms/step - loss: 1.7438 - acc: 0.2500 - val_loss: 1.5726 - val_acc: 0.2833
Epoch 2/8
360/360 [==============================] - 84s 232ms/step - loss: 1.4335 - acc: 0.4056 - val_loss: 1.6079 - val_acc: 0.3333
Epoch 3/8
360/360 [==============================] - 83s 232ms/step - loss: 1.2500 - acc: 0.5000 - val_loss: 1.7000 - val_acc: 0.3500
Epoch 4/8
360/360 [==============================] - 88s 245ms/step - loss: 1.0798 - acc: 0.5667 - val_loss: 1.9464 - val_acc: 0.3000
Epoch 5/8
 16/360 [>.............................] - ETA: 1:18 - loss: 0.7122 - acc: 0.6875Traceback (most recent call last):
  File "cnn.py", line 99, in <module>
    main()
  File "cnn.py", line 28, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 54, in build_cnn
    model.fit(X_train, y_train, batch_size=8, validation_data=(X_test, y_test), epochs=8)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
KeyboardInterrupt

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has 360, validation data has 60
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "cnn.py", line 100, in <module>
    main()
  File "cnn.py", line 28, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 45, in build_cnn
    model.add(Dropout(0.2))
NameError: name 'Dropout' is not defined

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has 360, validation data has 60
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 360 samples, validate on 60 samples
Epoch 1/8
2019-04-27 15:25:00.622167: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
360/360 [==============================] - 103s 286ms/step - loss: 1.7535 - acc: 0.1944 - val_loss: 1.6085 - val_acc: 0.3500
Epoch 2/8
360/360 [==============================] - 102s 283ms/step - loss: 1.4405 - acc: 0.4278 - val_loss: 1.5912 - val_acc: 0.3000
Epoch 3/8
360/360 [==============================] - 103s 286ms/step - loss: 1.1953 - acc: 0.5139 - val_loss: 1.8821 - val_acc: 0.3000
Epoch 4/8
360/360 [==============================] - 105s 291ms/step - loss: 0.9853 - acc: 0.6250 - val_loss: 1.9418 - val_acc: 0.3500
Epoch 5/8
 32/360 [=>............................] - ETA: 1:29 - loss: 0.8464 - acc: 0.6562Traceback (most recent call last):
  File "cnn.py", line 98, in <module>
    main()
  File "cnn.py", line 26, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 53, in build_cnn
    model.fit(X_train, y_train, batch_size=8, validation_data=(X_test, y_test), epochs=8)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
KeyboardInterrupt

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has 360, validation data has 60
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Traceback (most recent call last):
  File "cnn.py", line 98, in <module>
    main()
  File "cnn.py", line 26, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 47, in build_cnn
    model.add(Dense(6, activation='softmax', kernel_regularizer=regularizers.l2(0.003)))
NameError: name 'regularizers' is not defined

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has 360, validation data has 60
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 360 samples, validate on 60 samples
Epoch 1/2
2019-04-27 15:38:09.249818: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
360/360 [==============================] - 104s 288ms/step - loss: 1.7882 - acc: 0.2444 - val_loss: 1.6569 - val_acc: 0.3500
Epoch 2/2
360/360 [==============================] - 102s 282ms/step - loss: 1.5119 - acc: 0.3861 - val_loss: 1.6080 - val_acc: 0.3167

(env) C:\Users\Emre\Documents\ML_EEG\src>git add -A

(env) C:\Users\Emre\Documents\ML_EEG\src>git commit -m "added additional regularization to training"
[master 0d55380] added additional regularization to training
 3 files changed, 8 insertions(+), 13 deletions(-)
 create mode 100644 new_results.PNG
 create mode 100644 overfitting.PNG

(env) C:\Users\Emre\Documents\ML_EEG\src>git push origin master
fatal: HttpRequestException encountered.
   An error occurred while sending the request.
Counting objects: 6, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 26.09 KiB | 8.70 MiB/s, done.
Total 6 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/perlGivesMeNightmares/comp_5450_eeg.git
   eabfd92..0d55380  master -> master

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has 360, validation data has 60
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 360 samples, validate on 60 samples
Epoch 1/3
2019-04-27 16:09:20.937902: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
360/360 [==============================] - 105s 293ms/step - loss: 1.7854 - acc: 0.2361 - val_loss: 1.6195 - val_acc: 0.3333
Epoch 2/3
360/360 [==============================] - 104s 289ms/step - loss: 1.5021 - acc: 0.4028 - val_loss: 1.5621 - val_acc: 0.3333
Epoch 3/3
360/360 [==============================] - 104s 288ms/step - loss: 1.3745 - acc: 0.5000 - val_loss: 1.6735 - val_acc: 0.3333
Traceback (most recent call last):
  File "cnn.py", line 101, in <module>
    main()
  File "cnn.py", line 27, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 56, in build_cnn
    plot_model(model, to_file='model.png')
NameError: name 'plot_model' is not defined

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has 360, validation data has 60
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 360 samples, validate on 60 samples
Epoch 1/3
2019-04-27 16:15:13.820408: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
360/360 [==============================] - 101s 281ms/step - loss: 1.7554 - acc: 0.2583 - val_loss: 1.6365 - val_acc: 0.3667
Epoch 2/3
360/360 [==============================] - 100s 277ms/step - loss: 1.4764 - acc: 0.4222 - val_loss: 1.6498 - val_acc: 0.3833
Epoch 3/3
360/360 [==============================] - 100s 279ms/step - loss: 1.3335 - acc: 0.4778 - val_loss: 1.7796 - val_acc: 0.3000
Traceback (most recent call last):
  File "cnn.py", line 101, in <module>
    main()
  File "cnn.py", line 27, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 56, in build_cnn
    plot_model(model, to_file='model.png')
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\utils\vis_utils.py", line 132, in plot_model
    dot = model_to_dot(model, show_shapes, show_layer_names, rankdir)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\utils\vis_utils.py", line 55, in model_to_dot
    _check_pydot()
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\utils\vis_utils.py", line 20, in _check_pydot
    'Failed to import `pydot`. '
ImportError: Failed to import `pydot`. Please install `pydot`. For example with `pip install pydot`.

(env) C:\Users\Emre\Documents\ML_EEG\src>pip install pydot
Collecting pydot
  Downloading https://files.pythonhosted.org/packages/33/d1/b1479a770f66d962f545c2101630ce1d5592d90cb4f083d38862e93d16d2/pydot-1.4.1-py2.py3-none-any.whl
Requirement already satisfied: pyparsing>=2.1.4 in c:\users\emre\documents\ml_eeg\env\lib\site-packages (from pydot) (2.3.1)
Installing collected packages: pydot
Successfully installed pydot-1.4.1

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has 360, validation data has 60
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 360 samples, validate on 60 samples
Epoch 1/4
2019-04-27 16:23:01.906068: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
360/360 [==============================] - 102s 284ms/step - loss: 1.8140 - acc: 0.2194 - val_loss: 1.7545 - val_acc: 0.3667
Epoch 2/4
360/360 [==============================] - 99s 275ms/step - loss: 1.5542 - acc: 0.4417 - val_loss: 1.6320 - val_acc: 0.3333
Epoch 3/4
 48/360 [===>..........................] - ETA: 1:28 - loss: 1.3561 - acc: 0.4583Traceback (most recent call last):
  File "cnn.py", line 106, in <module>
    main()
  File "cnn.py", line 27, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 54, in build_cnn
    model.fit(X_train, y_train, batch_size=16, validation_data=(X_test, y_test), epochs=4)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
KeyboardInterrupt

(env) C:\Users\Emre\Documents\ML_EEG\src>
(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has 360, validation data has 60
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 360 samples, validate on 60 samples
Epoch 1/3
2019-04-27 16:26:55.100280: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
360/360 [==============================] - 100s 277ms/step - loss: 1.8333 - acc: 0.2639 - val_loss: 1.7635 - val_acc: 0.2667
Epoch 2/3
360/360 [==============================] - 100s 277ms/step - loss: 1.5897 - acc: 0.4056 - val_loss: 1.5757 - val_acc: 0.3000
Epoch 3/3
360/360 [==============================] - 100s 278ms/step - loss: 1.3543 - acc: 0.4639 - val_loss: 1.6041 - val_acc: 0.3333
Traceback (most recent call last):
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\pydot.py", line 1915, in create
    working_dir=tmp_dir,
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\pydot.py", line 136, in call_graphviz
    **kwargs
  File "c:\users\emre\appdata\local\programs\python\python35\Lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "c:\users\emre\appdata\local\programs\python\python35\Lib\subprocess.py", line 955, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\utils\vis_utils.py", line 26, in _check_pydot
    pydot.Dot.create(pydot.Dot())
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\pydot.py", line 1922, in create
    raise OSError(*args)
FileNotFoundError: [WinError 2] "dot" not found in path.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cnn.py", line 57, in build_cnn
    plot_model(model, to_file='model.png')
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\utils\vis_utils.py", line 132, in plot_model
    dot = model_to_dot(model, show_shapes, show_layer_names, rankdir)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\utils\vis_utils.py", line 55, in model_to_dot
    _check_pydot()
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\utils\vis_utils.py", line 29, in _check_pydot
    '`pydot` failed to call GraphViz.'
OSError: `pydot` failed to call GraphViz.Please install GraphViz (https://www.graphviz.org/) and ensure that its executables are in the $PATH.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cnn.py", line 106, in <module>
    main()
  File "cnn.py", line 27, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 60, in build_cnn
    model.save('./')
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\network.py", line 1090, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\saving.py", line 379, in save_model
    f = h5dict(filepath, mode='w')
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\utils\io_utils.py", line 186, in __init__
    self.data = h5py.File(path, mode=mode)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\h5py\_hl\files.py", line 394, in __init__
    swmr=swmr)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\h5py\_hl\files.py", line 176, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 105, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = './', errno = 13, error message = 'Permission denied', flags = 13, o_flags = 302)

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "cnn_example.py", line 58, in <module>
    main()
  File "cnn_example.py", line 22, in main
    X_train = X_train.reshape(60000,28,28,1) / 256
ValueError: cannot reshape array of size 3920000 into shape (60000,28,28,1)

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.
(5000, 28, 28, 1)
(5000, 10)

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.
(5000, 28, 28, 1)
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 5000 samples, validate on 1000 samples
Epoch 1/1
2019-04-27 16:36:41.640147: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
5000/5000 [==============================] - 13s 3ms/step - loss: 0.4688 - acc: 0.8610 - val_loss: 0.2210 - val_acc: 0.9320
Traceback (most recent call last):
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\pydot.py", line 1915, in create
    working_dir=tmp_dir,
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\pydot.py", line 136, in call_graphviz
    **kwargs
  File "c:\users\emre\appdata\local\programs\python\python35\Lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "c:\users\emre\appdata\local\programs\python\python35\Lib\subprocess.py", line 955, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\utils\vis_utils.py", line 26, in _check_pydot
    pydot.Dot.create(pydot.Dot())
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\pydot.py", line 1922, in create
    raise OSError(*args)
FileNotFoundError: [WinError 2] "dot" not found in path.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cnn_example.py", line 46, in main
    plot_model(model, to_file='./model.png')
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\utils\vis_utils.py", line 132, in plot_model
    dot = model_to_dot(model, show_shapes, show_layer_names, rankdir)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\utils\vis_utils.py", line 55, in model_to_dot
    _check_pydot()
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\utils\vis_utils.py", line 29, in _check_pydot
    '`pydot` failed to call GraphViz.'
OSError: `pydot` failed to call GraphViz.Please install GraphViz (https://www.graphviz.org/) and ensure that its executables are in the $PATH.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cnn_example.py", line 55, in <module>
    main()
  File "cnn_example.py", line 49, in main
    model.save('./')
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\network.py", line 1090, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\saving.py", line 379, in save_model
    f = h5dict(filepath, mode='w')
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\utils\io_utils.py", line 186, in __init__
    self.data = h5py.File(path, mode=mode)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\h5py\_hl\files.py", line 394, in __init__
    swmr=swmr)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\h5py\_hl\files.py", line 176, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 105, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = './', errno = 13, error message = 'Permission denied', flags = 13, o_flags = 302)

(env) C:\Users\Emre\Documents\ML_EEG\src>
(env) C:\Users\Emre\Documents\ML_EEG\src>pip install graphviz
Collecting graphviz
  Downloading https://files.pythonhosted.org/packages/1f/e2/ef2581b5b86625657afd32030f90cf2717456c1d2b711ba074bf007c0f1a/graphviz-0.10.1-py2.py3-none-any.whl
Installing collected packages: graphviz
Successfully installed graphviz-0.10.1

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.
(5000, 28, 28, 1)
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 5000 samples, validate on 1000 samples
Epoch 1/1
2019-04-27 16:45:58.536010: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
5000/5000 [==============================] - 13s 3ms/step - loss: 0.4723 - acc: 0.8634 - val_loss: 0.2031 - val_acc: 0.9380
Traceback (most recent call last):
  File "cnn_example.py", line 49, in main
    model.save('./')
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\network.py", line 1090, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\saving.py", line 379, in save_model
    f = h5dict(filepath, mode='w')
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\utils\io_utils.py", line 186, in __init__
    self.data = h5py.File(path, mode=mode)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\h5py\_hl\files.py", line 394, in __init__
    swmr=swmr)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\h5py\_hl\files.py", line 176, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 105, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = './', errno = 13, error message = 'Permission denied', flags = 13, o_flags = 302)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cnn_example.py", line 57, in <module>
    main()
  File "cnn_example.py", line 51, in main
    model.save('./')
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\network.py", line 1090, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\saving.py", line 379, in save_model
    f = h5dict(filepath, mode='w')
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\utils\io_utils.py", line 186, in __init__
    self.data = h5py.File(path, mode=mode)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\h5py\_hl\files.py", line 394, in __init__
    swmr=swmr)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\h5py\_hl\files.py", line 176, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 105, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = './', errno = 13, error message = 'Permission denied', flags = 13, o_flags = 302)

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.
(5000, 28, 28, 1)
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 5000 samples, validate on 1000 samples
Epoch 1/1
2019-04-27 16:46:30.400350: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
5000/5000 [==============================] - 13s 3ms/step - loss: 0.4687 - acc: 0.8590 - val_loss: 0.2474 - val_acc: 0.9170

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.
(5000, 28, 28, 1)
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 5000 samples, validate on 1000 samples
Epoch 1/1
2019-04-27 16:46:59.847109: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
5000/5000 [==============================] - 13s 3ms/step - loss: 0.4754 - acc: 0.8574 - val_loss: 0.2208 - val_acc: 0.9280
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x00000182BF0BEFD0>>
Traceback (most recent call last):
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\client\session.py", line 738, in __del__
TypeError: 'NoneType' object is not callable

(env) C:\Users\Emre\Documents\ML_EEG\src>git add -A

(env) C:\Users\Emre\Documents\ML_EEG\src>git commit -m "visualize"
[master 166938d] visualize
 5 files changed, 31 insertions(+), 15 deletions(-)
 create mode 100644 src/model.png

(env) C:\Users\Emre\Documents\ML_EEG\src>git push origin master
fatal: HttpRequestException encountered.
   An error occurred while sending the request.
Counting objects: 8, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 7.39 KiB | 7.39 MiB/s, done.
Total 8 (delta 5), reused 0 (delta 0)
remote: Resolving deltas: 100% (5/5), completed with 5 local objects.
To https://github.com/perlGivesMeNightmares/comp_5450_eeg.git
   0d55380..166938d  master -> master

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn_example.py
Using TensorFlow backend.
(5000, 28, 28, 1)
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 5000 samples, validate on 1000 samples
Epoch 1/1
2019-04-28 19:28:01.577211: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
5000/5000 [==============================] - 13s 3ms/step - loss: 0.4793 - acc: 0.8618 - val_loss: 0.2265 - val_acc: 0.9320

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has 360, validation data has 60
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Traceback (most recent call last):
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\pydot.py", line 1915, in create
    working_dir=tmp_dir,
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\pydot.py", line 136, in call_graphviz
    **kwargs
  File "c:\users\emre\appdata\local\programs\python\python35\Lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "c:\users\emre\appdata\local\programs\python\python35\Lib\subprocess.py", line 955, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\utils\vis_utils.py", line 26, in _check_pydot
    pydot.Dot.create(pydot.Dot())
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\pydot.py", line 1922, in create
    raise OSError(*args)
FileNotFoundError: [WinError 2] "dot" not found in path.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cnn.py", line 107, in <module>
    main()
  File "cnn.py", line 27, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 52, in build_cnn
    plot_model(model, to_file='./model.png')
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\utils\vis_utils.py", line 132, in plot_model
    dot = model_to_dot(model, show_shapes, show_layer_names, rankdir)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\utils\vis_utils.py", line 55, in model_to_dot
    _check_pydot()
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\utils\vis_utils.py", line 29, in _check_pydot
    '`pydot` failed to call GraphViz.'
OSError: `pydot` failed to call GraphViz.Please install GraphViz (https://www.graphviz.org/) and ensure that its executables are in the $PATH.

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has 360, validation data has 60
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has 360, validation data has 60
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 360 samples, validate on 60 samples
Epoch 1/4
2019-04-28 19:36:40.138882: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
360/360 [==============================] - 99s 274ms/step - loss: 1.8167 - acc: 0.1833 - val_loss: 1.7437 - val_acc: 0.3333
Epoch 2/4
 16/360 [>.............................] - ETA: 1:35 - loss: 1.7381 - acc: 0.2500Traceback (most recent call last):
  File "cnn.py", line 118, in <module>
    main()
  File "cnn.py", line 28, in main
    build_cnn(training_data, training_labels, testing_data, testing_labels)
  File "cnn.py", line 55, in build_cnn
    history = model.fit(X_train, y_train, batch_size=16, validation_data=(X_test, y_test), epochs=4)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\engine\training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
KeyboardInterrupt

(env) C:\Users\Emre\Documents\ML_EEG\src>python cnn.py
Using TensorFlow backend.
training data has 360, validation data has 60
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\keras\backend\tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From C:\Users\Emre\Documents\ML_EEG\env\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 360 samples, validate on 60 samples
Epoch 1/4
2019-04-28 19:38:36.378680: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
360/360 [==============================] - 95s 263ms/step - loss: 1.8215 - acc: 0.1917 - val_loss: 1.7384 - val_acc: 0.2667
Epoch 2/4
360/360 [==============================] - 94s 261ms/step - loss: 1.5425 - acc: 0.4028 - val_loss: 1.6786 - val_acc: 0.3000
Epoch 3/4
360/360 [==============================] - 94s 261ms/step - loss: 1.3855 - acc: 0.4750 - val_loss: 1.6774 - val_acc: 0.3667
Epoch 4/4
360/360 [==============================] - 94s 261ms/step - loss: 1.2394 - acc: 0.5500 - val_loss: 1.8683 - val_acc: 0.3667

(env) C:\Users\Emre\Documents\ML_EEG\src>git add -A

(env) C:\Users\Emre\Documents\ML_EEG\src>git commit -m "add visuals"
[master eed3578] add visuals
 5 files changed, 20 insertions(+), 8 deletions(-)
 create mode 100644 Figure_1.png
 create mode 100644 Figure_2.png
 rewrite src/model.png (99%)
 create mode 100644 training.PNG

(env) C:\Users\Emre\Documents\ML_EEG\src>git push oirign master
fatal: 'oirign' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(env) C:\Users\Emre\Documents\ML_EEG\src>git push origin master
fatal: HttpRequestException encountered.
   An error occurred while sending the request.
Counting objects: 8, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 103.88 KiB | 14.84 MiB/s, done.
Total 8 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/perlGivesMeNightmares/comp_5450_eeg.git
   166938d..eed3578  master -> master

(env) C:\Users\Emre\Documents\ML_EEG\src>doskey /History > ../history.txt

(env) C:\Users\Emre\Documents\ML_EEG\src>